checklists/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('projects.urls', namespace='projects')),
]

projects/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url( r'^$',                                              views.index,                           name='index'            ),
    url( r'^(?P<pk>[0-9]+)/$',                               views.show,                            name='detail'           ),
    url( r'^(?P<pk>[0-9]+)/active/$',                        views.show, { 'filter': 'active'    }, name='detail_active'    ),
    url( r'^(?P<pk>[0-9]+)/completed/$',                     views.show, { 'filter': 'completed' }, name='detail_completed' ),
    url( r'^create/$',                                       views.create,                          name='create'           ),
    url( r'^(?P<pk>[0-9]+)/update/$',                        views.update,                          name='update'           ),
    url( r'^(?P<pk>[0-9]+)/delete/$',                        views.delete,                          name='delete'           ),
    url( r'^(?P<pk>[0-9]+)/clear_completed/$',               views.clear_completed,                 name='clear_completed'  ),
    url( r'^(?P<pk>[0-9]+)/toggle/all/$',                    views.toggle_all,                      name='toggle_all'       ),
    url( r'^(?P<project_id>[0-9]+)/create/$',                views.create_task,                     name='create_task'      ),
    url( r'^(?P<project_id>[0-9]+)/update/(?P<pk>[0-9]+)/$', views.update_task,                     name='update_task'      ),
    url( r'^(?P<project_id>[0-9]+)/delete/(?P<pk>[0-9]+)/$', views.delete_task,                     name='delete_task'      ),
    url( r'^(?P<project_id>[0-9]+)/toggle/(?P<pk>[0-9]+)/$', views.toggle_task,                     name='toggle_task'      ),
]

projects/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def remaining_tasks_count(self):
        return self.task_set.active().count()

    def completed_tasks_count(self):
        return self.task_set.completed().count()

    def __str__(self):
        return self.name


class TaskQuerySet(models.QuerySet):

    def active(self):
        return self.filter(completed=False)

    def completed(self):
        return self.filter(completed=True)


class Task(models.Model):
    title      = models.CharField(max_length=200)
    completed  = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    project    = models.ForeignKey(Project)

    objects = TaskQuerySet.as_manager()

    def __str__(self):
        return self.title

projects/forms.py
# forms.py
from django.forms import ModelForm

from .models import Project, Task


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name']

    def clean_name(self):
        return self.cleaned_data.get('name', '').strip()


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title']

    def clean_title(self):
        return self.cleaned_data.get('title', '').strip()


class ToggleTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['completed']

projects/views.py
# views.py
from django.http import HttpResponseBadRequest
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import ensure_csrf_cookie
from django.shortcuts import get_object_or_404 as find
from django.utils import timezone

from .shortcuts import render_for

from .models import Project, Task
from .forms import ProjectForm, TaskForm, ToggleTaskForm


render_html = render_for('projects', '.html')
render_js   = render_for('projects', '.js', 'application/javascript')


def _ctx(project, **kwargs):
    kwargs['project'] = project
    # count the number of remaining tasks
    if 'remaining_tasks_count' not in kwargs:
        kwargs['remaining_tasks_count'] = project.remaining_tasks_count()
    # count the number of completed tasks
    if 'completed_tasks_count' not in kwargs:
        kwargs['completed_tasks_count'] = project.completed_tasks_count()
    return kwargs


@ensure_csrf_cookie
@require_http_methods(['GET'])
def index(request):
    projects = Project.objects.all()
    return render_html(request, 'index', { 'projects': projects })


@ensure_csrf_cookie
@require_http_methods(['GET'])
def show(request, pk, filter='all'):
    project = find(Project, pk=pk)
    context = { 'filter': filter }

    # retrieve project tasks with the specified filter
    if filter == 'active':
        context['tasks'] = project.task_set.active()
        # prevent a new db hit to count remaining tasks
        context['remaining_tasks_count'] = len(context['tasks'])
    elif filter == 'completed':
        context['tasks'] = project.task_set.completed()
        # prevent a new db hit to count completed tasks
        context['completed_tasks_count'] = len(context['tasks'])
    else:
        context['tasks'] = project.task_set.all()

    return render_html(request, 'show', _ctx(project, **context))


@require_http_methods(['POST'])
def create(request):
    form = ProjectForm(request.POST)
    if form.is_valid():
        project = form.save()
        return render_js(request, 'create', { 'project': project })
    else:
        return HttpResponseBadRequest()


@require_http_methods(['PUT'])
def update(request, pk):
    project = find(Project, pk=pk)
    form = ProjectForm(request.PUT, instance=project)
    if form.is_valid():
        project = form.save(commit=False)
        project.save(update_fields=['name'])
    else:
        project.name = form.initial['name'] # reset changes
    return render_js(request, 'update', { 'project': project })


@require_http_methods(['DELETE'])
def delete(request, pk):
    project = find(Project, pk=pk)
    project.delete()
    return render_js(request, 'delete', { 'pk': pk })


@require_http_methods(['DELETE'])
def clear_completed(request, pk):
    project = find(Project, pk=pk)
    query = project.task_set.completed()
    task_ids = list(query.values_list('pk', flat=True))
    query.delete()
    return render_js(request, 'clear_completed', _ctx(project, task_ids=task_ids))


@require_http_methods(['PUT'])
def toggle_all(request, pk):
    project = find(Project, pk=pk)
    completed = (request.PUT.get('completed', '0') == '1')
    query = project.task_set.filter(completed=not(completed))
    task_ids = list(query.values_list('pk', flat=True))
    query.update(completed=completed, updated_at=timezone.now())
    return render_js(request, 'toggle_all', _ctx(project, completed=completed, task_ids=task_ids))


@require_http_methods(['POST'])
def create_task(request, project_id):
    task = Task(project_id=project_id)
    form = TaskForm(request.POST, instance=task)
    if form.is_valid():
        task = form.save()
        return render_js(request, 'task_create', _ctx(task.project, task=task))
    else:
        return HttpResponseBadRequest()


@require_http_methods(['PUT'])
def update_task(request, pk, project_id):
    # fetch the task and verify the relationship (pk/project_id)
    task = find(Task, pk=pk, project_id=project_id)
    form = TaskForm(request.PUT, instance=task)
    if form.is_valid():
        task = form.save(commit=False)
        task.save(update_fields=['title'])
    elif not form.data.get('title', '').strip(): # empty title, just delete the task
        task.delete()
        return render_js(request, 'task_delete', _ctx(task.project, pk=pk))
    else:
        task.title = form.initial['title'] # reset changes
    return render_js(request, 'task_update', { 'task': task })


@require_http_methods(['PUT'])
def toggle_task(request, pk, project_id):
    # fetch the task with the related project and verify the relationship (pk/project_id)
    task = find(Task.objects.select_related('project'), pk=pk, project_id=project_id)
    form = ToggleTaskForm(request.PUT, instance=task)
    if form.is_valid():
        task = form.save(commit=False)
        task.save(update_fields=['completed'])
        return render_js(request, 'task_toggle', _ctx(task.project, task=task))
    else:
        return HttpResponseBadRequest()


@require_http_methods(['DELETE'])
def delete_task(request, pk, project_id):
    # fetch the task with the related project and verify the relationship (pk/project_id)
    task = find(Task.objects.select_related('project'), pk=pk, project_id=project_id)
    task.delete()
    return render_js(request, 'task_delete', _ctx(task.project, pk=pk))

projects/templates/projects/_footer.html
{# Local context: project, completed_tasks_count, remaining_tasks_count #}
{% if completed_tasks_count > 0 or remaining_tasks_count > 0 %}
  <footer class="footer">
    <span class="todo-count"><strong>{{remaining_tasks_count}}</strong> item{{remaining_tasks_count|pluralize}} left</span>
    <ul class="filters">
      <li>
        <a class="all" href="{% url 'projects:detail' project.id %}">All</a>
      </li>
      <li>
        <a class="active" href="{% url 'projects:detail_active' project.id %}">Active</a>
      </li>
      <li>
        <a class="completed" href="{% url 'projects:detail_completed' project.id %}">Completed</a>
      </li>
    </ul>
    {% if completed_tasks_count > 0 %}
      <a href="{% url 'projects:clear_completed' project.id %}"
        class="clear-completed"
        rel="nofollow"
        data-method="delete"
        data-remote="true"
        data-confirm="Are you sure you want to clear all completed tasks in &quot;{{project}}&quot;?&#10;This will permanently delete {{completed_tasks_count}} task{{completed_tasks_count|pluralize}}."
      >Clear completed</a>
    {% endif %}
  </footer>
{% else %}
  <footer class="footer" style="display:none" />
{% endif %}

projects/templates/projects/_project.html
{# Local context: project #}
<li id="project_{{project.id}}">
  <label><a href="{% url 'projects:detail' project.id %}">{{project}}</a></label>
  <a href="{% url 'projects:delete' project.id %}"
    class="destroy"
    rel="nofollow"
    data-method="delete"
    data-remote="true"
    data-confirm="Are you sure you want to delete &quot;{{project}}&quot;?"></a>
</li>

projects/templates/projects/_project_title.html
{# Local context: project #}
<h1>
  <div class="view">
    <label>{{project.name}}</label>
  </div>
  <form action="{% url 'projects:update' project.id %}" method="put" data-remote="true">
    <input name="name" class="edit" value="{{project.name}}" data-original-value="{{project.name}}" data-disable>
  </form>
</h1>

projects/templates/projects/_task.html
{# Local context: task #}
<li id="task_{{task.id}}" class="{% if task.completed %}completed{% endif %}">

  <div class="view">

    <input name="completed" class="toggle" type="checkbox" {% if task.completed %}checked{% endif %}
      data-remote="true"
      data-url="{% url 'projects:toggle_task' task.project_id task.id %}"
      data-method="put"
      value="1">

    <label>{{task.title}}</label>

    <a href="{% url 'projects:delete_task' task.project_id task.id %}"
      class="destroy"
      rel="nofollow"
      data-disable
      data-method="delete"
      data-remote="true"
      data-confirm="Are you sure you want to delete &quot;{{task}}&quot;?"></a>

  </div>

  <form action="{% url 'projects:update_task' task.project_id task.id %}" method="put" data-remote="true">
    <input name="title" class="edit" value="{{task.title}}" data-original-value="{{task.title}}" data-disable>
  </form>

</li>

projects/templates/projects/index.html
{% extends 'base.html' %}
{% block content %}
  <section class="todoapp">
    <header class="header">
      <h1>projects</h1>
      <form action="{% url 'projects:create' %}" method="post" data-remote="true">
        <input name="name" class="new-todo new-project" placeholder="New project?" autofocus>
      </form>
    </header>
    <section class="main">
      <ul class="todo-list project-list">
        {% for project in projects %}
          {% include 'projects/_project.html' with project=project %}
        {% endfor %}
      </ul>
    </section>
  </section>
{% endblock content %}

projects/templates/projects/show.html
{% extends 'base.html' %}
{% block content %}

  <div class="back">
    <a href="{% url 'projects:index' %}">&#9664; Back to project list</a>
  </div>

  <section class="todoapp filter-{{filter}}">

    <header class="header">
      {% include 'projects/_project_title.html' with project=project %}
      <form action="{% url 'projects:create_task' project.id %}" method="post" data-remote="true">
        <input name="title" class="new-todo" placeholder="What needs to be done?" autofocus>
      </form>
    </header>

    <section class="main" {% if tasks|length == 0 %}style="display:none"{% endif %}>
      <input name="completed" class="toggle-all" type="checkbox" value="1"
        data-url="{% url 'projects:toggle_all' project.id %}" data-method="put" data-remote="true"
        {% if remaining_tasks_count == 0 and completed_tasks_count > 0 %}checked{% endif %}>
      <label for="toggle-all">Mark all as complete</label>
      <ul class="todo-list">
        {% for task in tasks %}
          {% include 'projects/_task.html' with task=task %}
        {% endfor %}
      </ul>
    </section>

    {% include 'projects/_footer.html' %}

  </section>

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>todo • checklists</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'todomvc-app-css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css.css' %}">
  </head>
  <body>
    {% block content %}{% endblock content %}
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="{% static 'js.js' %}"></script>
  </body>
</html>